---
- name: Create download folder.
  ansible.builtin.file:
    path: "{{ download_folder }}"
    state: directory
    mode: 0600

- name: Download cuda toolkit runfile.
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ download_folder }}/cuda_runfile.run"
    mode: a+x
  with_items:
    - {
        url: https://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_440.33.01_linux.run,
        version: 10.2,
      }
    - {
        url: http://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda_11.0.2_450.51.05_linux.run,
        version: 11.0,
      }
    - {
        url: https://developer.download.nvidia.com/compute/cuda/11.2.0/local_installers/cuda_11.2.0_460.27.04_linux.run,
        version: 11.2.0,
      }
    - {
        url: https://developer.download.nvidia.com/compute/cuda/11.2.1/local_installers/cuda_11.2.1_460.32.03_linux.run,
        version: 11.2.1,
      }
    - {
        url: https://developer.download.nvidia.com/compute/cuda/11.2.2/local_installers/cuda_11.2.2_460.32.03_linux.run,
        version: 11.2.2,
      }
    - {
        url: https://developer.download.nvidia.com/compute/cuda/11.3.0/local_installers/cuda_11.3.0_465.19.01_linux.run,
        version: 11.3.0,
      }
    - {
        url: https://developer.download.nvidia.com/compute/cuda/11.3.1/local_installers/cuda_11.3.1_465.19.01_linux.run,
        version: 11.3.1,
      }
    - {
        url: https://developer.download.nvidia.com/compute/cuda/11.4.0/local_installers/cuda_11.4.0_470.42.01_linux.run,
        version: 11.4.0,
      }
    - {
        url: https://developer.download.nvidia.com/compute/cuda/11.4.1/local_installers/cuda_11.4.1_470.57.02_linux.run,
        version: 11.4.1,
      }
    - {
        url: https://developer.download.nvidia.com/compute/cuda/11.4.2/local_installers/cuda_11.4.2_470.57.02_linux.run,
        version: 11.4.2,
      }
    - {
        url: https://developer.download.nvidia.com/compute/cuda/11.4.3/local_installers/cuda_11.4.3_470.82.01_linux.run,
        version: 11.4.3,
      }
    - {
        url: https://developer.download.nvidia.com/compute/cuda/11.5.0/local_installers/cuda_11.5.0_495.29.05_linux.run,
        version: 11.5.0,
      }
    - {
        url: https://developer.download.nvidia.com/compute/cuda/11.5.1/local_installers/cuda_11.5.1_495.29.05_linux.run,
        version: 11.5.1,
      }
  when: item.version == cuda_version

- name: Install cuda toolkit.
  ansible.builtin.shell:
    cmd: "./cuda_runfile.run --silent --toolkit --toolkitpath={{ toolkit_install_folder }}/cuda-{{ cuda_version }} --defaultroot={{ toolkit_install_folder }}/cuda-{{ cuda_version }} --no-man-page --override"
    chdir: "{{ download_folder }}"

- name: Copy modulefile.
  ansible.builtin.template:
    src: cuda.lua.j2
    dest: "{{ modulefile_folder }}/cuda-{{ cuda_version }}.lua"
    owner: ansible
    group: ansible
    mode: 0775
  when: create_modulefile and modulefile_folder is defined
