---
- name: Check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against CentOS 7 and 8 or Ubuntu 20. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: (ansible_distribution|lower == 'centos' and ansible_distribution_major_version is version_compare('7', '<')) or
        (ansible_distribution|lower == 'centos' and ansible_distribution_major_version is version_compare('8', '>')) or
        (ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version is version_compare('20', '!='))

- name: "Check OS version and family"
  ansible.builtin.debug:
    msg: "PASS | This role can only be executed on CentOS 7 and 8 and Ubuntu 20 operating systems, detected {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  when: (ansible_distribution|lower == 'centos' and ansible_distribution_major_version is version_compare('7', '==')) or
        (ansible_distribution|lower == 'centos' and ansible_distribution_major_version is version_compare('8', '==')) or
        (ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version is version_compare('20', '=='))


- include_tasks: install.yml